#!/usr/bin/env perl
use strict;
use warnings;

use v5.14;

use CBOR::XS;

use Zonemaster::Engine::Nameserver;
use Zonemaster::Engine::Packet;

# Decode input into packets
my $cbor = CBOR::XS->new();
my $saved_contents = $cbor->decode(do { local $/; <> });

my $format_version = $saved_contents->{format_version};
say ";;;;";
say ";;;; START OF METADATA";
say ";;;; FORMAT VERSION: ", $saved_contents->{format_version};
say ";;;; ENGINE VERSION: ", $saved_contents->{engine_version};
say ";;;; END OF METADATA";
say ";;;;";
say "";

my @entries =
    map {
        my ( $name, $ip, $request, $response ) = @$_;
        [
            $name,
            $ip,
            Zonemaster::Engine::Packet->new({ packet => Zonemaster::LDNS::Packet->new_from_wireformat($request) }),
            Zonemaster::Engine::Nameserver::_deserialize_packet($response)
        ]
    }
    map { my ($ns, $entries) = @$_; map { [ @$ns, @$_ ] } @$entries }
    @{$saved_contents->{packets}};

# Print delimited packets
my $delim = (";" x 78 . "\n") x 3;
for my $entry ( @entries ) {
    my ( $ns, $ip, $request, $response ) = @$entry;
    say $delim;

    my $flags = $request->id();
    say ";; Query to $ns ($ip) ",
        ($flags & (1 << 15) ? "over TCP" : "over UDP");

    say request_to_string($request), "\n";
    if (defined $response) {
        say $response->string;
    }
    else {
        say ";; No response from name server.";
    }
    say "";
}


# Modify the string representation of the request slightly so it doesn’t look
# too much like its response, and more like what dig +qr would show.
sub request_to_string {
    my ( $request ) = @_;

    my @lines = split( "\n", $request->string );
    $lines[0] =~ s/, id: \d+$//;
    my $result = join( "\n", @lines[0..3] );

    if (my ( $edns ) = grep { /^;; EDNS: / } @lines) {
        $result .= "\n$edns";
    }
    if (my ( $msg_size ) = grep { /^;; MSG SIZE  rcvd: \d+$/ } @lines) {
        $result .= "\n" . ($msg_size =~ s/rcvd/sent/r);
    }

    return $result;
}


=head1 NAME

    data2dig - Export saved Zonemaster::Engine cache files to a dig format


=head1 SYNOPSIS

    data2dig foo.data


=head1 DESCRIPTION

B<data2dig> exports saved Zonemaster::Engine cache files to human readable
format as packets in dig format.

=cut

