#!/bin/bash
#
# Description:
#
#   Update PO files with fresh msgids from source.
#
#   It's just a frontend for util/extract_po.pl and msgmerge.
#
#   Note that the environment variable MSGMERGE_OPTS can be used to give additional arguments to msgmerge.
#
# Synopsis:
#
#   util/update_po share/*.po
#
#   MSGMERGE_OPTS=--no-fuzzy-matching util/update_po share/*.po


# Abort if anything fails
set -e

# Create temp directory and make sure it gets cleaned up
tempdir="$(mktemp -d)"
trap "{ rm -rf $tempdir; }" EXIT

# Create PO template for the (presumably) latest sources
ref_pot="${tempdir}/ref.pot"
perl -Ilib util/extract_po.pl > "${ref_pot}"

# Loop over input file arguments
while [ $# -ge 1 ] ; do
    def_po="${1}" ; shift

    # Update existing PO using new template
    # (Using temp file to avoid truncating input file before reading it)
    temp_po="${tempdir}/temp.po"
    echo -n "${def_po}: "
    msgmerge ${MSGMERGE_OPTS} "${def_po}" "${ref_pot}" | sed 's/^msgid "/msgid  "/' > "${temp_po}"
    mv "${temp_po}" "${def_po}"
done
